services:
  # 1. FINORA Backend REST API Service
  - type: web
    name: finora-backend
    runtime: node
    rootDir: backend
    plan: free
    region: oregon
    buildCommand: npm install --include=dev && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        value: '*'
